### ISSUE TITLE
Poisson source spikes from multiple 1ms runs don't get recorded.

### ISSUE THREAD

**Issue by 366anna** [SpiNNakerManchester/sPyNNaker8#102] opened 2018-01-04 10:30 UTC
When I run a bunch of 1ms runs, the poisson source spikes don't seem to be recorded. And if I change dt to 2ms, they do. 

```
import spynnaker8 as p

from pyNN.utility.plotting import Figure, Panel, DataTable

import matplotlib.pyplot as plt

import numpy as np



pre_rate = 100

nrn = 1

dt=1



p.setup(1)



simtime = 100



pop_src = p.Population(nrn, p.SpikeSourcePoisson(rate=pre_rate), label="src")

pop_src.record('spikes')



for i in range(simtime/dt):

        print i

        p.run(dt)



pre_spikes = pop_src.get_data('spikes')

plot_time = simtime

Figure(

    # raster plot of the presynaptic neuron spike times

     Panel(pre_spikes.segments[0].spiketrains,

           yticks=True, markersize=0.5, xlim=(0, plot_time), xticks=True, data_labels=['pre-spikes']),

    annotations="Simulated with {}".format(p.name()))

plt.show()



p.end()

print "\n job done"
```

**Comment by Christian-B** [comment] 2019-04-16 15:03
This is caused by the method SpikeSourcePoissonVertex._max_spikes_per_ts being WRONG

At only 1 timestep (chance_ts)
        max_spikes_per_ts = scipy.stats.poisson.ppf(
            1.0 - (1.0 / float(chance_ts)),
            float(max_rate) / ts_per_second)

has 1.0 - 1.0  so zero

Therefor this function returns zero

And no space is saved to record the spikes.

**Comment by Christian-B** [comment] 2019-04-16 15:05
Note: The sdram_per_timestep branches reserve the max possible space and in these branches this problem does not occur as _max_spikes_per_ts is called with the much higher values.

Still worth fixing the function however.

**Comment by andrewgait** [comment] 2019-04-23 12:14
@Christian-B this seems related to your recent work - is this case still broken?

**Comment by Christian-B** [comment] 2019-04-23 12:22
in https://github.com/SpiNNakerManchester/sPyNNaker/pull/580 
method SpikeSourcePoissonVertex._max_spikes_per_ts 
no longer depends on the time being run

Therefor https://github.com/SpiNNakerManchester/sPyNNaker/pull/580 solved this.

Closing in anticipation.

**Closed by Christian-B** 2019-04-23 12:22 UTC
