### ISSUE TITLE
Reusing connector instances leads to unexpected behaviour

### ISSUE THREAD

**Issue by tophensen** [SpiNNakerManchester/sPyNNaker8#157] opened 2018-06-27 10:47 UTC
In PyNN 0.8 and 0.9 synapses and connectors are meant to be (almost) orthogonal properties of a projection. In spynnaker8, however, the weights and delays of, e.g., a StaticSynapse will modify the connector. This leads to unexpected behaviour if the same Connector instance is given to multiple different projections: The Projection handles last will determine the weights and delays of all Projections, because it is the same connector holding the weights and delays.

In the long run it might be worthwhile to separate Synapses and Connectors in sPyNNaker, but a short term fix would be to copy() the connector object before modifying any of its properties here:

https://github.com/SpiNNakerManchester/sPyNNaker8/blob/666e58deb04d5ccf3340417bc5f3d8ab1cef3e17/spynnaker8/models/projection.py#L57

**Comment by andrewgait** [comment] 2018-06-27 11:16
I've been looking at this recently in https://github.com/SpiNNakerManchester/sPyNNaker8/pull/150 (which depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/525) - this is waiting to be merged because there's a few other big changes coming, however if you want the correct behaviour when the same Connector is given to multiple Projections then these two branches should still work at the moment.

(Effectively this is a duplicate of https://github.com/SpiNNakerManchester/sPyNNaker/issues/519 but we'll keep it alive in this repository as well until it gets merged.)

**Comment by andrewgait** [comment] 2019-03-07 10:40
PR #525 has been merged so closing this issue.

**Closed by andrewgait** 2019-03-07 10:40 UTC
Labels: bug
